#define SUCCESS_STATE 0

//#define MAX_TEXT_SIZE 8192
//#define MAX_WORD_COUNT (MAX_TEXT_SIZE / 5)
//#define MAX_LEXEM_SIZE 1024
//#define MAX_VARIABLES_COUNT 256
//#define MAX_KEYWORD_COUNT 64
//
//#define KEYWORD_LEXEME_TYPE 1
//#define IDENTIFIER_LEXEME_TYPE 2 // #define LABEL_LEXEME_TYPE 8
//#define VALUE_LEXEME_TYPE 4
//#define UNEXPEXTED_LEXEME_TYPE 127
//
//#define LEXICAL_ANALISIS_MODE 1
//#define SEMANTIC_ANALISIS_MODE 2
//#define FULL_COMPILER_MODE 4
//
//#define DEBUG_MODE 512
//
//+!///#define MAX_PARAMETERS_SIZE 4096
//+!///#define PARAMETERS_COUNT 4
//+!///#define INPUT_FILENAME_PARAMETER 0
//
//#define DEFAULT_MODE (LEXICAL_ANALISIS_MODE | DEBUG_MODE)